[package]
name = "odyn-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "odyn"
path = "src/main.rs"

[dependencies]
anstream = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
odyn-core = { path = "../odyn-core" }
rustyline = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
